### ISSUE TITLE
Tara_launch: Tried to advertise a service that is already advertised in this node [/stereo/set_camera_info]

### ISSUE THREAD

**Issue by Changliu52** [dilipkumar25/see3cam#13]
It seems the tara node is trying to advertise two [/stereo/set_camera_info] rosservice, rather than [stereo/left/set_camera_info] and [stereo/right/set_camera_info]

Please update this, because this is very important for running the stereoCalibration in ros.

Kind Regards,
Chang

**Comment by jveitchmichaelis** [comment]
Hi @Changliu52 - please check out our fork here; https://github.com/i3drobotics/deimos-ros

It doesn't look like PRs are being accepted here, hence the shameless plug :)

I've made a number of modifications to the package (including fixing this issue). It's designed for our Deimos stereo system, but should be compatible with your camera.

**Comment by void-robotics** [comment]
Is this package still being supported? I'm also seeing the same double advertisement message.

The deimos one sort of worked for me; some rendering issues in ROS kinetic

**Comment by jveitchmichaelis** [comment]
@nathangeorge1 What rendering issues are you seeing? I can take a look if you like. Otherwise you could probably take inspiration from the Deimos package and use it to modify this one if it seems to work better, though we haven't altered the bulk of the code, just fixed some of the topics.

@hellozhouuu care to comment on the thumbs down? If you're having issues I'd be happy to help.

**Comment by void-robotics** [comment]
@jveitchmichaelis sure; let me open an issue on your GitHub repo

**Comment by Changliu52** [comment]
Great! Thanks
