### ISSUE TITLE
Topic (/stereo/image_raw) rendering issue

### ISSUE THREAD

**Issue by farhanmubasher** [dilipkumar25/see3cam#14]
**Hi,**
First of all thanks for everything,
I've successfully run the package, every topic is giving fine results except  /stereo/image_raw, when i run this topic the video streaming looks like everything is shaking or everything in video has its projection.

I have shared two images for better understanding:

**This is the result image of topic /stereo/concat:**
![image](https://user-images.githubusercontent.com/22928889/50518991-a5946b00-0ab0-11e9-85f5-4a98cb2ad2d7.png)

**This is the result image of topic /stereo/image_raw:**
![image2](https://user-images.githubusercontent.com/22928889/50519046-dd9bae00-0ab0-11e9-9ae2-20c33baabe11.png)

I don't know why it looks like blurry or shaking, can you please help me with this.
**I'm using Tara stereo cam on Jetson Tx2 board.**
Thanks in advance.

**Comment by akhileshmalviya** [comment]
@farhanmubasher As the topic name (**/stereo/image_raw**) implies, it's just a raw image of the stereo camera. Since the **Tara stereo cam** has two sensors, it outputs the image with all the information, got by both sensors, in interleaved form. So don't worry, the image is not blurry or shaking, it's just the **raw image**.

**Comment by farhanmubasher** [comment]
Thank you for your help man
